"use client";

import { useEffect, useState } from "react";

type Status = "Operational" | "Maintenance" | "Outage" | "Paused";
type Monitor = { id: number; name: string; type: string; target: string; status: Status; uptime: number; ms: number; reason?: string; checkedAt: string };
type Tab = "Overview" | "Monitors" | "Incidents" | "Public page" | "Domains" | "Settings";

const seed: Monitor[] = [
  { id: 1, name: "Production API", type: "HTTPS health check", target: "api.northstar.dev/health", status: "Operational", uptime: 99.98, ms: 43, checkedAt: "just now" },
  { id: 2, name: "Discord bot", type: "Discord /health endpoint", target: "bot.northstar.dev/health", status: "Operational", uptime: 99.92, ms: 57, checkedAt: "just now" },
  { id: 3, name: "Marketing site", type: "HTTPS health check", target: "northstar.dev", status: "Maintenance", uptime: 99.76, ms: 0, reason: "Scheduled content deployment in progress.", checkedAt: "14 min ago" },
];

const history = (status: Status) => Array.from({ length: 18 }, (_, i) => status === "Outage" && i > 11 ? "red" : status === "Maintenance" && i > 12 ? "amber" : status === "Paused" ? "gray" : "green");

export default function Home() {
  const [screen, setScreen] = useState<"landing" | "demo" | "public">("landing");
  const [monitors, setMonitors] = useState<Monitor[]>(seed);
  const [tab, setTab] = useState<Tab>("Overview");
  const [showAdd, setShowAdd] = useState(false);
  const [tour, setTour] = useState(true);
  const [pageName, setPageName] = useState("Northstar Studio");
  const [accent, setAccent] = useState("#245c36");
  const [domain, setDomain] = useState("");
  const [domainSaved, setDomainSaved] = useState(false);
  const [plan, setPlan] = useState<"Free" | "Starter">("Starter");
  const [form, setForm] = useState({ name: "", type: "HTTPS health check", target: "https://" });
  const [toast, setToast] = useState("");
  const say = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2600); };
  const changePlan = (next: "Free" | "Starter") => { if (next === "Free" && monitors.length > 1) return say("Free allows one monitor. Remove monitors first, or stay on Starter."); setPlan(next); say(`Switched demo to ${next}`); };
  const exitDemo = () => { setScreen("landing"); setMonitors(seed); setTab("Overview"); setShowAdd(false); setTour(true); setPageName("Northstar Studio"); setAccent("#245c36"); setDomain(""); setDomainSaved(false); setPlan("Starter"); };
  const addMonitor = () => {
    const limit = plan === "Starter" ? 5 : 1;
    if (monitors.length >= limit) return say(`${plan} allows ${limit} monitor${limit === 1 ? "" : "s"}. Switch plans in Settings.`);
    if (!form.name.trim() || form.target.trim() === "https://") return say("Add a name and a target first");
    setMonitors((items) => [...items, { id: Date.now(), name: form.name.trim(), type: form.type, target: form.target.trim(), status: "Operational", uptime: 100, ms: 38, checkedAt: "just now" }]);
    setForm({ name: "", type: "HTTPS health check", target: "https://" }); setShowAdd(false); setTab("Monitors"); say("Monitor added in demo mode");
  };
  const remove = (id: number) => { setMonitors((items) => items.filter((m) => m.id !== id)); say("Monitor removed from demo"); };
  const togglePause = (id: number) => setMonitors((items) => items.map((m) => m.id === id ? { ...m, status: m.status === "Paused" ? "Operational" : "Paused", ms: m.status === "Paused" ? 38 : 0, checkedAt: m.status === "Paused" ? "just now" : "paused" } : m));
  if (screen === "public") return <Public pageName={pageName} monitors={monitors} accent={accent} domain={domainSaved ? domain : "pulsestatus.livmellow.com/northstar"} back={() => setScreen("demo")} />;
  return <main>
    {screen === "landing" ? <Landing monitors={monitors} go={() => setScreen("demo")} /> : <Dashboard {...{ monitors, setMonitors, tab, setTab, showAdd, setShowAdd, tour, setTour, pageName, setPageName, accent, setAccent, domain, setDomain, domainSaved, setDomainSaved, form, setForm, addMonitor, remove, togglePause, say, plan, setPlan: changePlan }} preview={() => setScreen("public")} exit={exitDemo} />}
    {toast && <div className="toast" role="status">Saved: {toast}</div>}
  </main>;
}

function Mark() { return <span className="mark">P</span>; }
function Landing({ monitors, go }: { monitors: Monitor[]; go: () => void }) { return <>
  <nav className="landingnav"><a className="logo"><Mark />pulse<b>status</b></a><div><button onClick={go} className="textbtn">Demo workspace</button><button onClick={go} className="primary">Start free</button></div></nav>
  <section className="hero2"><p className="kicker"><i /> UPTIME MADE HUMAN</p><h1>Trust is built<br /><em>between incidents.</em></h1><p>Pulse Status gives every service a clear, beautiful home before something goes wrong.</p><div><button onClick={go} className="primary big">Explore the live demo -&gt;</button><button onClick={go} className="textbtn big">See how it works</button></div><small>No credit card - Free plan included</small></section>
  <section className="miniPublic"><div className="url">status.northstar.dev <b>{aggregate(monitors).label}</b></div><h2>Northstar Studio</h2><p>Live service status</p><StatusRows monitors={monitors.slice(0, 2)} /></section>
  <section className="landingStats"><div><b>60 sec</b><span>fast check interval</span></div><div><b>5</b><span>monitors on Starter</span></div><div><b>90 days</b><span>uptime history</span></div></section>
  <section className="pitch"><div><p className="kicker">BUILT TO CLARIFY</p><h2>Not another dashboard.<br />A better customer experience.</h2></div><div className="pCards"><article><b>01</b><h3>Know first</h3><p>Health checks watch websites, APIs, ports, IP addresses, and Discord bots every minute.</p></article><article><b>02</b><h3>Explain clearly</h3><p>Automatic incidents catch problems; simple updates tell people what is happening.</p></article><article><b>03</b><h3>Look like you</h3><p>Every public page uses your logo, colors, domain, and voice.</p></article></div></section>
  <section className="priceBand"><div><p className="kicker">SIMPLE PRICING</p><h2>Start free.<br />Grow calmly.</h2><p>One monitor is free forever. Starter is $5/month for five monitors, a custom domain, and 90-day history.</p></div><div className="plan"><span>STARTER</span><strong>$5<small>/mo</small></strong><p>5 monitors - 90 days - custom domain</p><button onClick={go} className="primary">Try demo mode</button></div></section>
</>;
}

function Dashboard(p: any) {
  const active = p.monitors.filter((m: Monitor) => m.status === "Operational").length;
  const incidents = p.monitors.filter((m: Monitor) => m.status === "Maintenance" || m.status === "Outage");
  const avg = p.monitors.length ? (p.monitors.reduce((n: number, m: Monitor) => n + m.uptime, 0) / p.monitors.length).toFixed(2) : "-";
  const fastest = p.monitors.filter((m: Monitor) => m.ms > 0).sort((a: Monitor, b: Monitor) => a.ms - b.ms)[0]?.ms;
  const limit = p.plan === "Starter" ? 5 : 1;
  return <div className="app"><aside><button className="logo brandButton" onClick={() => p.setTab("Overview")}><Mark />pulse<b>status</b></button><div className="workspace"><i>NS</i><b>{p.pageName}</b><small>{p.plan} demo</small></div><nav aria-label="Dashboard"><Nav tab={p.tab} setTab={p.setTab} monitors={p.monitors.length} /></nav><div className="sidefoot"><button onClick={() => p.setTab("Settings")}>Settings</button><button onClick={p.exit}>Exit demo</button></div></aside><section className="dash"><div className="mobileNav"><select aria-label="Dashboard section" value={p.tab} onChange={(e) => p.setTab(e.target.value as Tab)}>{(["Overview", "Monitors", "Incidents", "Public page", "Domains", "Settings"] as Tab[]).map(x => <option key={x}>{x}</option>)}</select></div><header><div><p className="kicker">DEMO WORKSPACE</p><h1>{p.tab === "Overview" ? "Your services, at a glance." : p.tab}</h1><p className="sub">Changes reset when you exit demo mode.</p></div><button className="outline previewTarget" onClick={p.preview}>View public page</button></header><div className="notice"><i /><div><b>Demo mode is on</b><span>Build a status page safely, then connect a real account when you are ready.</span></div><button onClick={() => p.setTour(true)}>Restart tour</button></div>
    {p.tab === "Overview" && <><div className="metrics"><Metric value={`${active}/${p.monitors.length || 0}`} label="Operational now" /><Metric value={`${avg}%`} label="Average uptime" /><Metric value={fastest ? `${fastest}ms` : "-"} label="Fastest response" /><Metric value={String(incidents.length)} label="Active incidents" /></div><Usage used={p.monitors.length} limit={limit} plan={p.plan} setPlan={p.setPlan} /><MonitorTable monitors={p.monitors} add={() => p.setShowAdd(true)} remove={p.remove} togglePause={p.togglePause} cap={p.monitors.length >= limit} /></>}
    {p.tab === "Monitors" && <><Usage used={p.monitors.length} limit={limit} plan={p.plan} setPlan={p.setPlan} /><MonitorTable monitors={p.monitors} add={() => p.setShowAdd(true)} remove={p.remove} togglePause={p.togglePause} cap={p.monitors.length >= limit} /></>}
    {p.tab === "Incidents" && <Incidents monitors={p.monitors} setMonitors={p.setMonitors} say={p.say} />}
    {p.tab === "Public page" && <PublicPanel pageName={p.pageName} setPageName={p.setPageName} accent={p.accent} setAccent={p.setAccent} preview={p.preview} />}
    {p.tab === "Domains" && <Domains domain={p.domain} setDomain={p.setDomain} saved={p.domainSaved} save={() => { p.setDomainSaved(true); p.say("Domain setup saved in demo"); }} />}
    {p.tab === "Settings" && <Settings pageName={p.pageName} setPageName={p.setPageName} accent={p.accent} setAccent={p.setAccent} plan={p.plan} setPlan={p.setPlan} say={p.say} />}
  </section>
  {p.showAdd && <AddDialog form={p.form} setForm={p.setForm} close={() => p.setShowAdd(false)} add={p.addMonitor} />}
  {p.tour && <Tour close={() => p.setTour(false)} add={() => { p.setTour(false); p.setShowAdd(true); }} preview={p.preview} />}
  </div>;
}

function Nav({ tab, setTab, monitors }: { tab: Tab; setTab: (tab: Tab) => void; monitors: number }) { return <>{(["Overview", "Monitors", "Incidents", "Public page", "Domains"] as Tab[]).map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}{item === "Monitors" && <em>{monitors}</em>}</button>)}</>; }
function Usage({ used, limit, plan, setPlan }: any) { return <div className="usage"><div><b>{plan} plan preview</b><span>{used}/{limit} monitors used</span></div><div className="usagebar"><i style={{ width: `${Math.min(100, used / limit * 100)}%` }} /></div><button className="outline" onClick={() => setPlan(plan === "Starter" ? "Free" : "Starter")}>Switch to {plan === "Starter" ? "Free" : "Starter"}</button></div>; }
function MonitorTable({ monitors, add, remove, togglePause, cap }: any) { return <><div className="sectionhead"><div><h2>Monitors</h2><p>Demo checks run as sample data. Real checks will run every 60 seconds.</p></div><button className="primary addTarget" onClick={add} disabled={cap}>{cap ? "Monitor limit reached" : "+ Add monitor"}</button></div>{monitors.length === 0 ? <div className="empty"><div className="bigmark">+</div><h2>Add your first monitor</h2><p>Start with a website, API, port, IP address, or Discord bot health endpoint.</p><button className="primary" onClick={add}>Add monitor</button></div> : <div className="table"><div className="thead"><span>Monitor</span><span>Status</span><span>Uptime</span><span>Response</span><span>Actions</span></div>{monitors.map((m: Monitor) => <div className="trow" key={m.id}><div><b>{m.name}</b><small>{m.type} - {m.target}</small><small>Last checked {m.checkedAt}</small></div><StatusBadge status={m.status} /><div><b>{m.uptime}%</b><History status={m.status} /></div><span>{m.ms ? `${m.ms}ms` : "-"}</span><div className="actions"><button onClick={() => togglePause(m.id)}>{m.status === "Paused" ? "Resume" : "Pause"}</button><button onClick={() => remove(m.id)}>Delete</button></div></div>)}</div>}</>; }
function Incidents({ monitors, setMonitors, say }: any) { const incidents = monitors.filter((m: Monitor) => m.status === "Maintenance" || m.status === "Outage"); const create = () => { const target = monitors.find((m: Monitor) => m.status === "Operational"); if (!target) return say("Resume a monitor before opening another incident"); setMonitors((all: Monitor[]) => all.map(m => m.id === target.id ? { ...m, status: "Outage", ms: 0, reason: "We are investigating an issue in demo mode.", checkedAt: "just now" } : m)); say("Incident created and published"); }; const resolve = (id: number) => { setMonitors((all: Monitor[]) => all.map(m => m.id === id ? { ...m, status: "Operational", reason: undefined, ms: 42, checkedAt: "just now" } : m)); say("Incident resolved"); }; return <><div className="sectionhead"><div><h2>Incidents</h2><p>Keep customers informed with a reason and automatic recovery updates.</p></div><button className="primary" onClick={create}>+ Create incident</button></div>{incidents.length ? incidents.map((m: Monitor) => <div className="incidentCard" key={m.id}><div className="warning">!</div><div><b>{m.name} {m.status.toLowerCase()}</b><p>{m.reason || "We are investigating this service."}</p><small>Started 14 minutes ago - updates post to the public page</small></div><StatusBadge status={m.status} /><button className="outline" onClick={() => resolve(m.id)}>Resolve</button></div>) : <div className="empty"><div className="bigmark">OK</div><h2>No active incidents</h2><p>When a monitor fails repeatedly, Pulse Status will open an incident here.</p></div>}</>; }
function PublicPanel({ pageName, setPageName, accent, setAccent, preview }: any) { const slug = pageName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "status"; return <div className="formcard"><span>BRANDING</span><h1>Your public page</h1><p>Customize the exact page your customers will see.</p><label>Page name<input value={pageName} onChange={(e) => setPageName(e.target.value)} /></label><label>Logo initials<input maxLength={3} value={pageName.split(" ").map((x: string) => x[0]).join("").slice(0, 3)} readOnly aria-label="Demo logo initials" /></label><label>Accent color<input type="color" value={accent} onChange={(e) => setAccent(e.target.value)} /></label><label>Public URL<input value={`pulsestatus.livmellow.com/${slug}`} readOnly /></label><button className="primary" onClick={preview}>Preview public page</button></div>; }
function Domains({ domain, setDomain, saved, save }: any) { return <div className="formcard"><span>CUSTOM DOMAIN</span><h1>Bring your own domain</h1><p>Enter a domain and we will give you the records needed to verify it.</p><label>Domain<input value={domain} onChange={(e) => setDomain(e.target.value)} placeholder="status.yourcompany.com" /></label><button className="primary" onClick={save} disabled={!domain}>Generate DNS records</button>{saved && <div className="dns"><b>Add these records at your DNS provider</b><p>CNAME: <code>{domain}</code> to <code>domains.pulsestatus.livmellow.com</code></p><p>TXT: <code>_pulse-status.{domain}</code> = <code>pulse-verify-demo</code></p></div>}<small>Router port forwarding is not needed.</small></div>; }
function Settings({ pageName, setPageName, accent, setAccent, plan, setPlan, say }: any) { return <div className="formcard"><span>PAGE SETTINGS</span><h1>Make it feel like you</h1><p>Settings update the public preview immediately in demo mode.</p><label>Organization name<input value={pageName} onChange={(e) => setPageName(e.target.value)} /></label><label>Accent color<input type="color" value={accent} onChange={(e) => setAccent(e.target.value)} /></label><label>Demo plan<select value={plan} onChange={(e) => setPlan(e.target.value)}><option>Free</option><option>Starter</option></select></label><button className="primary" onClick={() => say("Brand settings saved in demo")}>Save changes</button></div>; }
function AddDialog({ form, setForm, close, add }: any) { useEffect(() => { const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") close(); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [close]); return <div className="dialog" role="dialog" aria-modal="true" aria-label="Add a monitor" onMouseDown={(e) => { if (e.target === e.currentTarget) close(); }}><div><button className="close" onClick={close} aria-label="Close">x</button><p className="kicker">NEW MONITOR</p><h2>Add a service</h2><label>Name<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Production API" autoFocus /></label><label>Check type<select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}><option>HTTPS health check</option><option>HTTP keyword check</option><option>Discord /health endpoint</option><option>TCP port</option><option>Ping / IP address</option></select></label><label>URL or target<input value={form.target} onChange={(e) => setForm({ ...form, target: e.target.value })} /></label><button className="primary full" onClick={add}>Add monitor</button><small>Press Escape or click outside to close.</small></div></div>; }
function Tour({ close, add, preview }: { close: () => void; add: () => void; preview: () => void }) { const [step, setStep] = useState(1); useEffect(() => { const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") close(); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [close]); return <div className="tourShade" role="dialog" aria-modal="true" aria-label="Quick dashboard tour"><div className={step === 1 ? "spotlight addSpotlight" : "spotlight previewSpotlight"} /><div className="tourCard"><p className="kicker">WELCOME TO PULSE STATUS - {step}/2</p><h2>{step === 1 ? "Start with one service." : "See what customers see."}</h2><p>{step === 1 ? "The highlighted Add monitor button is where you add a website, API, port, IP address, or Discord health endpoint." : "Your public page turns monitor data and incident updates into a clear customer experience."}</p><div>{step === 1 ? <button className="primary" onClick={() => setStep(2)}>Next: public preview</button> : <button className="primary" onClick={() => { close(); preview(); }}>Open public preview</button>}<button className="textbtn" onClick={close}>Skip for now</button></div><small>Press Escape to skip. You can restart this tour from the demo notice.</small></div></div>; }
function Metric({ value, label }: { value: string; label: string }) { return <div className="metric"><b>{value}</b><span>{label}</span></div>; }
function StatusBadge({ status }: { status: Status }) { return <span className={`badge ${status.toLowerCase()}`}>{status}</span>; }
function History({ status }: { status: Status }) { return <div className="bar">{history(status).map((tone, i) => <i key={i} className={tone} />)}</div>; }
function StatusRows({ monitors }: { monitors: Monitor[] }) { return <>{monitors.map((m) => <div className="publicRow" key={m.id}><div><b><i className={`dot ${m.status.toLowerCase()}`} /> {m.name}</b><small>{m.target}</small></div><History status={m.status} /><StatusBadge status={m.status} /></div>)}</>; }
function aggregate(monitors: Monitor[]) { const active = monitors.filter(m => m.status !== "Paused"); if (active.some((m) => m.status === "Outage")) return { tone: "outage", label: "An outage is affecting some services", headline: <>We are investigating an <em>outage.</em></> }; if (active.some((m) => m.status === "Maintenance")) return { tone: "maintenance", label: "Maintenance in progress", headline: <>Some services are under <em>maintenance.</em></> }; return { tone: "operational", label: "All active systems operational", headline: <>Everything is <em>operational.</em></> }; }
function Public({ pageName, monitors, accent, domain, back }: { pageName: string; monitors: Monitor[]; accent: string; domain: string; back: () => void }) { const current = aggregate(monitors); const incidents = monitors.filter((m) => m.reason); const initials = pageName.split(" ").map(x => x[0]).join("").slice(0, 3); return <main className="public" style={{ "--brand": accent } as React.CSSProperties}><nav><button className="logo brandButton" onClick={back}><span style={{ background: accent }}>{initials}</span>{pageName}</button><button className="textbtn" onClick={back}>Back to demo</button></nav><section><p className="kicker">SERVICE STATUS</p><h1>{current.headline}</h1><p>We monitor our systems continuously and share clear updates here.</p><div className="publicPanel"><div className="url">{domain}</div><div className={`publicBanner ${current.tone}`}>{current.label}</div><StatusRows monitors={monitors} /><div className="publicIncident"><b>Recent updates</b>{incidents.length ? incidents.map((m) => <p key={m.id}><strong>{m.name}:</strong> {m.reason} <small>Started 14 minutes ago</small></p>) : <p>No active incidents or planned maintenance.</p>}</div><div className="subscribe"><div><b>Stay in the loop</b><small>Demo notification signups are disabled until launch.</small></div><button className="outline" disabled>Launching soon</button></div></div></section><footer>Powered by Pulse Status</footer></main>; }
